"""New Migration

Revision ID: 0f91b71981b1
Revises: 88cd622ec3e5
Create Date: 2024-04-20 14:55:00.448161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f91b71981b1'
down_revision = '88cd622ec3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_time', sa.DateTime(), nullable=False))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    with op.batch_alter_table('alert_result', schema=None) as batch_op:
        batch_op.drop_column('completion_time')

    # ### end Alembic commands ###
