"""New Migration

Revision ID: 19420a014781
Revises: 0f91b71981b1
Create Date: 2024-04-20 14:58:32.505086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19420a014781'
down_revision = '0f91b71981b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responders')
    # ### end Alembic commands ###
