"""empty message

Revision ID: 818886c63325
Revises: 3c3444f1a42f
Create Date: 2024-04-22 13:57:19.165806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818886c63325'
down_revision = '3c3444f1a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
