"""Remove submitter column from Emergency table

Revision ID: b14b7c0fcb1a
Revises: ceb336a199dc
Create Date: 2024-04-21 18:37:26.140613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b14b7c0fcb1a'
down_revision = 'ceb336a199dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_death', sa.DateTime(), nullable=True))
        batch_op.drop_column('time_until_death')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_until_death', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('time_of_death')

    # ### end Alembic commands ###
