"""empty message

Revision ID: c73079c074fd
Revises: f8328e4443d1
Create Date: 2024-04-22 17:48:15.275202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73079c074fd'
down_revision = 'f8328e4443d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responder_name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('responders_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['responder_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('responders_name_key', ['name'])
        batch_op.drop_column('responder_name')

    # ### end Alembic commands ###
