"""empty message

Revision ID: fea0f8103c2a
Revises: 
Create Date: 2024-04-23 09:18:07.639305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea0f8103c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=80), nullable=False),
    sa.Column('client_ids', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('time_of_death', sa.DateTime(), nullable=True),
    sa.Column('injuries', sa.String(length=80), nullable=True),
    sa.Column('crime_stat', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergency.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responder_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responder_name')
    )
    op.create_table('alert_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=80), nullable=False),
    sa.Column('completion_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_result')
    op.drop_table('responders')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('emergency')
    # ### end Alembic commands ###
